# Git aliases for common cmds
alias gstatus='git status'
alias gstat='gstatus'
alias gadd='git add .'
alias gpush='git push'
alias gpull='git pull'
alias gcommit='git commit'
alias gdiff='git diff'
alias glog='git log'
alias gclone='git clone'

# Common export Bash variables
export EDITOR="/usr/bin/vim"

# Docker aliases for common cmds
alias dimg='docker images'
alias dimgs='docker images'
alias dps='docker ps'
alias drun='docker run'
alias dstart='docker start'
alias dstop='docker stop'
alias drm='docker rm'
alias drmi='docker rmi'
alias dbuild='docker build'
alias dinspect='docker inspect'
alias dnet='docker network'
alias dexec='docker exec'
alias dlogs='docker logs'
alias dpull='docker pull'
alias dpush='docker push'
alias dtag='docker tag'

# Docker aliases (specific)
alias drund='docker run -d'
alias dstopall='dstop `dps -aq`'
alias drmall='drm `dps -aq`'
alias dexecit='docker exec -it'
alias drunonce='drun -it --rm'
alias drunitrm='drun -it --rm'

# Docker-Compose aliases
alias dcom='docker-compose'
alias dcrun='docker-compose run'
alias dcup='docker-compose up'
alias dcdown='docker-compose down'
alias dcbuild='docker-compose build'

# Docker-Compose aliases (specific)
alias dcrunonce='docker-compose run --rm'
